version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${APP_NAME}:latest
    container_name: ${APP_NAME}
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge